### PR TITLE
League stats

### PR DESCRIPTION
**Pull request by kevingloss**
League Stats will merge a functioning best offense method with all of the related tests and helper methods.

Helper methods are kept in game_teams_manager and could be helpful for several other methods if expanded on.

### CODE REVIEW

**Comment by kevingloss** [comment]
Updated to include worst season as well.

**Review by LelandCurtis — APPROVED** [review]
great helper methods. Love how we have methods in Team class and the manager classes. This is all looking good.

**Review by echon006 — APPROVED** [review]
transfer of methods looks good

**Comment by kevingloss** [comment]
Updated this one more time and it now has all the league methods and related tests.

**Pull request merged**
